# Generated by Django 2.1.1 on 2020-06-08 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('bus_no', models.CharField(max_length=200)),
                ('bus_serial_no', models.IntegerField()),
                ('driver_name', models.CharField(max_length=200)),
                ('starting_point', models.CharField(max_length=200)),
                ('stoppage', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bus_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('add_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
