# Generated by Django 2.1.1 on 2020-06-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_serial_no',
            field=models.CharField(max_length=200),
        ),
    ]
