# Generated by Django 2.1.1 on 2020-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_auto_20200608_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
